apiVersion: v1
kind: ConfigMap
metadata:
  name: yelp-lab2-env
  namespace: yelp-lab2
data:
  APP_ROOT: "/app"
  MONGODB_DB_NAME: "yelp_lab2"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  MONGODB_URL: "mongodb://mongo:27017"
  # For AWS, override with DocumentDB URI:
  # MONGODB_URL: "mongodb://<docdb-endpoint>:27017"
