apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-worker
  namespace: yelp-lab2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: review-worker
  template:
    metadata:
      labels:
        app: review-worker
    spec:
      containers:
        - name: review-worker
          image: yelp-review-worker:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: yelp-lab2-env
