apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-worker
  namespace: yelp-lab2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: review-worker
  template:
    metadata:
      labels:
        app: review-worker
    spec:
      containers:
        - name: review-worker
          image: 839408459700.dkr.ecr.us-west-2.amazonaws.com/yelp-lab2:review-worker
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: yelp-lab2-env
